DECLARE  
    V_TEMP  NUMBER := &TEMP;
    V_QUENTE  EXCEPTION;
    V_FRIO  EXCEPTION;
    
BEGIN
   CASE 
     WHEN V_TEMP < 90.00 THEN RAISE V_FRIO;
     WHEN V_TEMP < 140.00 THEN RAISE V_QUENTE;
     ELSE NULL;

END CASE;
DBMS_OUTPUT.PUT_LINE('A TEMPERATURA ESTÁ BOA ');
EXCEPTION 
    WHEN VALUE_ERROR THEN
         DBMS_OUTPUT.PUT_LINE('POR FAVOR INSERIR UMA TEMPERATURA DE VALOR NUMÉRICO (COMO 100) ');
    WHEN V_QUENTE THEN
         DBMS_OUTPUT.PUT_LINE('O TEMPO ESTÁ MUITO QUENTE... ');
    WHEN V_FRIO THEN 
    DBMS_OUTPUT.PUT_LINE('O TEMPO ESTÁ MUITO FRIO... ');
    
END;


         
         