CREATE TABLE TEMPO (
ID INT PRIMARY KEY,
DIA INT,
MES INT,
ANO INT,
DATA INT
);



DROP TABLE TEMPO;

SELECT * FROM TEMPO;
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (1, 15, 1, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (2, 15, 2, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (3, 15, 3, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (4, 15, 4, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (5, 15, 5, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (6, 15, 6, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (7, 15, 7, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (8, 15, 8, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (9, 15, 9, 1999);
INSERT INTO TEMPO (ID, DIA, MES, ANO) VALUES (10, 15, 10, 1999);


  CREATE OR REPLACE PROCEDURE PRC_TEMPO( P_VALOR_QUALQUER IN NUMBER) IS
  CURSOR C1 IS
  SELECT * FROM TEMPO;
  BEGIN
    FOR X IN C1 LOOP
    UPDATE TEMPO
    SET DATA_TOTAL = (X.DIA + X.MES + X.ANO) + P_VALOR_QUALQUER
    WHERE ID = X.ID;
    END LOOP;
  END;

    
    
    DECLARE  
    
    V_NUM NUMBER:= &NUMERO;
    
    BEGIN
    
    for c2 in (select * from tempo) loop  
      PRC_TEMPO(V_NUM);
      DBMS_OUTPUT.PUT_LINE('Deu certo!');
     
      END LOOP;
    END;

    
    
    
  
        
    







