CREATE TABLE PRODUTO (
CODIGO NUMBER(4) PRIMARY KEY,
NOME VARCHAR2(20),
VALOR NUMBER(7,2),
CATEGORIA NUMBER(4)
);


CREATE OR REPLACE PROCEDURE PRC_PROD(P_NOVOS_DADOS_PRODUTO IN NUMBER,
                                     P_CODIGO IN PRODUTO.CODIGO%TYPE,
                                     P_VALOR_PRODUTO IN PRODUTO.VALOR%TYPE)IS
                                     
                                    
BEGIN

INSERT INTO PRODUTO
  VALUES (P_CODIGO, P_VALOR_PRODUTO);

EXCEPTION

 WHEN DUP_VAL_ON_INDEX THEN
 DBMS_OUTPUT.PUT_LINE ('Código de produto já cadastrado');

    UPDATE PRODUTO
    SET VALOR =  (P_NOVOS_DADOS_PRODUTO * P_CODIGO)  / 100
    WHERE CODIGO = X.CODIGO;
 
END;




EXECUTE(NOVOS_DADOS_PRODUTO);

INSERT INTO PRODUTO VALUES (1, 'PRODUTO1', 2.5, 10);
INSERT INTO PRODUTO VALUES (2, 'PRODUTO2', 3.2,20);
INSERT INTO PRODUTO VALUES (3, 'PRODUTO3', 5.8, 30);
        
         