CREATE OR REPLACE TRIGGER TRIGGER_CHAVE_ESTRANGEIRA
    AFTER UPDATE ON TB_AREA_REFERENCIA REFERENCING OLD AS ANTIGO NEW AS NOVO FOR EACH ROW
        
        BEGIN
          
          IF :ANTIGO.ID_EMP = 1   THEN
          
          INSERT INTO TB_AREA_COPIA 
          VALUES (:NOVO.ID_AREA, :NOVO.DESC_AREA,:NOVO.RESPONSAVEL, USER, TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS', :NOVO.ID_EMP));
          
        END IF;  
       END;
       
       
       SELECT * FROM TB_EMPRESA_REFERENCIA;
       
        DROP TABLE TB_AREA_REFERENCIA;
        
       
       CREATE TABLE TB_AREA_REFERENCIA(
         ID_AREA INT PRIMARY KEY,
         DESC_AREA VARCHAR2(30),
         RESPONSAVEL VARCHAR2(20),
         USUARIO VARCHAR2(50),
         DATA_HORA VARCHAR2(50),
         ID_EMP INT,
         FOREIGN KEY (ID_EMP) REFERENCES TB_ESTRANGEIRA_EMPRESA (ID_EMPRESA) 
       
       );
       
       
       
       DROP TABLE TB_AREA_COPIA;
       
       
       CREATE TABLE TB_AREA_COPIA(
       ID_AREA INT ,
       DESC_AREA VARCHAR2(50),
       RESPONSAVEL VARCHAR2(20),
       ID_EMP INT,
       USUARIO_ATUAL VARCHAR2(30),
       DATA_HORA_ATUAL VARCHAR2(60)    
       
       
       );
       
       
      CREATE TABLE TB_ESTRANGEIRA_EMPRESA( 
       ID_EMPRESA INT PRIMARY KEY,
       NOME_EMPRESA VARCHAR2(50),
       CNPJ VARCHAR2(15)         
       
       );
       
       DROP TABLE TB_ESTRANGEIRA_EMPRESA;

       
       INSERT INTO TB_ESTRANGEIRA_EMPRESA (ID_EMPRESA, NOME_EMPRESA, CNPJ) VALUES (1,'Solve Plan','5722625743' );
       INSERT INTO TB_ESTRANGEIRA_EMPRESA (ID_EMPRESA, NOME_EMPRESA, CNPJ) VALUES (2,'HOTMART','09653427' );

       UPDATE TB_AREA_REFERENCIA SET RESPONSAVEL = 'ANDREY' WHERE ID_AREA = 102;
       UPDATE TB_AREA_REFERENCIA SET RESPONSAVEL = 'PAULO' WHERE ID_AREA = 103;
       
       
       INSERT INTO TB_AREA_REFERENCIA values (101, 'Analitics ', 'André', USER, TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 1);
       INSERT INTO TB_AREA_REFERENCIA values (102, 'Comercial ', 'João', USER, TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 1);
       INSERT INTO TB_AREA_REFERENCIA values (103, 'Vendas ', 'Marcelo', USER, TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 2);
       INSERT INTO TB_AREA_REFERENCIA values (104, 'Desenvolvimento ', 'Diego', USER, TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'), 2);
       
       
        SELECT * FROM TB_ESTRANGEIRA_EMPRESA;
        SELECT * FROM TB_AREA_REFERENCIA;
        SELECT * FROM TB_AREA_COPIA;
        
        
        
       
        
        
          SELECT  * FROM  TB_AREA_REFERENCIA, TB_ESTRANGEIRA_EMPRESA  WHERE ID_EMP = ID_EMPRESA;
          
          SELECT  TB_AREA_REFERENCIA.DESC_AREA, TB_AREA_REFERENCIA.RESPONSAVEL , TB_ESTRANGEIRA_EMPRESA.NOME_EMPRESA FROM  TB_AREA_REFERENCIA, TB_ESTRANGEIRA_EMPRESA  WHERE ID_EMP = ID_EMPRESA;
        
        
        
        
        
        
        
        
        

         