  CREATE OR REPLACE TRIGGER TRIGGER_ALTERACAO
       AFTER UPDATE ON TB_REFERENCIA REFERENCING OLD AS ANTIGO NEW AS NOVO FOR EACH ROW 
     BEGIN
        INSERT INTO TB_MUDANCAS VALUES (:ANTIGO.ID, :NOVO.ID, :ANTIGO.NOME, :NOVO.NOME, :ANTIGO.IDADE, :NOVO.IDADE, :ANTIGO.ENDERECO,
            :NOVO.ENDERECO, USER, TO_CHAR(SYSDATE, 'DD-MM-YYYY HH24:MI:SS'));
  END;



CREATE TABLE TB_REFERENCIA (ID INT, NOME VARCHAR2(50), IDADE INT,  ENDERECO VARCHAR2(70));
CREATE TABLE TB_MUDANCAS (A_ID INT, N_ID INT, A_NOME VARCHAR2(50), N_NOME VARCHAR2(50), A_IDADE INT , N_IDADE INT , A_ENDERECO VARCHAR2(50),
N_ENDERECO VARCHAR2(50), USUARIO_ATUAL VARCHAR2(50), DATA_HORA VARCHAR2(50));
INSERT INTO TB_REFERENCIA VALUES (1, 'VINICIUS', '19', 'Rua Agua Marinha, 455');
INSERT INTO TB_REFERENCIA VALUES (2, 'THAYNA SOUZA', '22', 'Rua OSCAR FREIRE, 6722');
INSERT INTO TB_REFERENCIA VALUES (3, 'JORGE JESUS', '55', 'AV IPANEMA, 5004');
UPDATE TB_REFERENCIA SET NOME = 'OSCAR', IDADE = 65 WHERE ID = 1;
UPDATE TB_REFERENCIA SET NOME = 'VINICIUS', IDADE = '19' WHERE ID = 2;
UPDATE TB_REFERENCIA SET NOME = 'OSCAR' WHERE ID = 1;
SELECT * FROM TB_REFERENCIA;
SELECT * FROM TB_MUDANCAS;
