CREATE TABLE EMPRESA(
ID INT PRIMARY KEY,
NOME_EMPRESA VARCHAR (30),
CNPJ INT,
ENDERECO VARCHAR (60)

);


CREATE TABLE EMPRESA_COPIA(
ID INT PRIMARY KEY,
NOME_EMPRESA VARCHAR (30),
CNPJ INT,
ENDERECO VARCHAR (60),
USUARIO VARCHAR (40),
DATA_LOG DATE

);


create or replace TRIGGER TRIGGERAUDITORIA 
AFTER INSERT

ON EMPRESA


BEGIN

   INSERT INTO EMPRESA_COPIA (NOME_EMPRESA,CNPJ,ENDERECO,USUARIO,DATA_LOG) VALUES('SOLVE','0923778334','Av Jabaquara 1090', USER ,TO_CHAR (SYSDATE, 'DD-MM-YYYY HH24:MI:SS'));

  NULL;
END;

INSERT INTO EMPRESA (NOME_EMPRESA,CNPJ,ENDERECO) VALUES ('SOLVE','0923778334','Av Jabaquara 1090');

SELECT * FROM EMPRESA;
SELECT * FROM EMPRESA_COPIA;






CREATE TABLE AUDIT01(
TABELA VARCHAR (40),
ACAO VARCHAR(10),
USUARIO VARCHAR(50)
DATA_HORA 

);


create or replace TRIGGER TRIGGERAUDITORIA 
AFTER INSERT

ON EMPRESA


BEGIN

INSERT INTO EMPRESA (NOME_EMPRESA,CNPJ,ENDERECO) VALUES ('SOLVE','0923778334','Av Jabaquara 1090');


  NULL;
END;